#!/bin/bash
#записываем дату в айл
date >> /home/titov/dev/userspace
#команда, которая показывает размер директории каждого пользователя
du -sh /home/* | cut -d "/" -f 1,3 | tr -d "/" >> /home/titov/dev/userspace
