#!/bin/bash

#set variables
USER=titov

#https://docs.docker.com/engine/install/debian/
#if u install docker on machine with docker, delete it first
#sudo apt-get remove docker docker-engine docker.io containerd runc

#then, update you're system
sudo apt-get update -y
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y

#Add Docker’s official GPG key
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

#set up the stable repository
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

#Install Docker Engine
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

#create group
sudo groupadd docker
sudo usermod -aG docker $USER
#or sudo usermod -aG docker whoami
